main: fr.enderstevegamer.arcanauhc.Main
name: ArcanaUHC
description: Le plugin utilisé pour l'Arcana UHC
author: Endersteve_gamer
version: 1.0
api-version: 1.8.8
commands:
  config:
    description: Utilisé pour configurer la partie
    usage: /config
    aliases: [cg]
  equipstartingstuff:
    description: Utilisé pour équiper un stuff de départ à une personne
    usage: /equipstartingstuff <player>
    aliases: [startingstuff]
  setgamename:
    description: Utilisé pour redéfinir le nom de la partie
    usage: /setgamename <nom de la partie>
    aliases: [gamename]
  doc:
    description: Affiche le lien du Gitbook du mode de jeu
    usage: /doc
    aliases: [dc]