main: fr.enderstevegamer.arcanauhc.Main
name: ArcanaUHC
description: Le plugin utilisé pour l'Arcana UHC
author: Endersteve_gamer
version: 1.0
api-version: 1.8.8
commands:
  config:
    description: Utilisé pour configurer la partie
    usage: /config